#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define SIDE_TOP 1
#define SIDE_DOWN 2
#define SIDE_LEFT 3
#define SIDE_RIGHT 4

#define ANIMATION_IDLE 0
#define ANIMATION_WALK 1
#define ANIMATION_MINE 2
#define ANIMATION_JUMP 3
#define ANIMATION_DEAD 4
#define ANIMATION_DEADED 5

#define ANIMATION_SIDE_OFFSET 6

#define TILE_WIDTH 10
#define TILE_HEIGHT 10

#define TILE_AIR 0
#define TILE_GRASS 1
#define TILE_GRASS_DECAL 2
#define TILE_DIRT 3
#define TILE_STONE 4
#define TILE_COAL 5
#define TILE_IRON 6
#define TILE_GOLD 7
#define TILE_EMERALD 8
#define TILE_WOOD 9
#define TILE_IMMORTAL_AIR 10
#define TILE_OBSIDIAN 11
#define TILE_SAND 12
#define TILE_MOON_ROCK 13
#define TILE_MOON_COAL 14
#define TILE_MOON_IRON 15
#define TILE_MOON_GOLD 16
#define TILE_MOON_EMERALD 17
#define TILE_MOON_TORF 18

#define TILE_TYPES 19
#define MAX_LAYERS 30

#define GOD_SPEED_MULTIPLIER 3.f

#define SCORE_TO_TIME_RATIO 0.3f
#define SHEEP_HOLE_SIZE 10
#define SHEEP_HOLE_MARGIN 50
#define SHEEP_WIN_DISTANCE 5.0f

#define DEFINED_MAPS 5
